name: jsca_xf_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  connectivity: ^3.0.6
  url_launcher: ^6.1.9
  provider: ^6.0.5
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - assets/dist/
  fonts:
      - family: iconfont
        fonts:
          - asset: lib/asset/iconfont.ttf